export type ApiContext = IServer.ApiContext;
export type ApiErrorResponse = IServer.ApiErrorResponse;
export type ApiHandler = IServer.ApiHandler;
export type ApiMiddleware = IServer.ApiMiddleware;
export type ApiResponse<T = unknown> = IServer.ApiResponse<T>;
export type AuthUser = IServer.AuthUser;
export type ErrorType = IServer.ErrorType;
export type LogLevel = IServer.LogLevel;
export type PaginatedResponse<T = unknown> = IServer.PaginatedResponse<T>;
export type RouteParams = IServer.RouteParams;
