import { type ReactNode } from 'react';
import type { Metadata } from 'next';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { AntdProvider } from '@/components';
import { APP_NAME } from '@/constants';
import 'antd/dist/reset.css';
import '@/styles/globals.css';

export const metadata: Metadata = {
  title: APP_NAME,
  description: 'Generated by nextjs blank template',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <meta
        name="viewport"
        content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no,viewport-fit=cover"
      />
      <meta httpEquiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
      <link rel="apple-touch-icon" sizes="57x57" href="/icon/apple-icon-57x57.png" />
      <link rel="apple-touch-icon" sizes="60x60" href="/icon/apple-icon-60x60.png" />
      <link rel="apple-touch-icon" sizes="72x72" href="/icon/apple-icon-72x72.png" />
      <link rel="apple-touch-icon" sizes="76x76" href="/icon/apple-icon-76x76.png" />
      <link rel="apple-touch-icon" sizes="114x114" href="/icon/apple-icon-114x114.png" />
      <link rel="apple-touch-icon" sizes="120x120" href="/icon/apple-icon-120x120.png" />
      <link rel="apple-touch-icon" sizes="144x144" href="/icon/apple-icon-144x144.png" />
      <link rel="apple-touch-icon" sizes="152x152" href="/icon/apple-icon-152x152.png" />
      <link rel="apple-touch-icon" sizes="180x180" href="/icon/apple-icon-180x180.png" />
      <link rel="icon" type="image/png" sizes="192x192" href="/icon/android-icon-192x192.png" />
      <link rel="icon" type="image/png" sizes="32x32" href="/icon/favicon-32x32.png" />
      <link rel="icon" type="image/png" sizes="96x96" href="/icon/favicon-96x96.png" />
      <link rel="icon" type="image/png" sizes="16x16" href="/icon/favicon-16x16.png" />
      <link rel="manifest" href="/icon/manifest.json" />
      <meta name="msapplication-TileColor" content="#fff" />
      <meta name="msapplication-TileImage" content="/icon/ms-icon-144x144.png" />
      <meta name="theme-color" content="#fff" />
      <body>
        <AntdRegistry>
          <AntdProvider>{children}</AntdProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
